## This my my practice so far with Tensorflow

In [1]:
import platform
print(platform.python_version())

3.7.4


In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.1.0


In [4]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

# Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(
    AB_concatenated.numpy()
))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]


In [5]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
    A
))

The transposed matrix A:
[[3 1]
 [7 9]]


In [7]:
A = tf.constant([[3, 7],
                [1, 9]])

v = tf.constant([[5],
                [2]])

Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new tensor:\n{0}').format(Av))

Matrix Multiplication of A and v results in a new tensor:
[[29]
 [23]]


In [8]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1

In [9]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [10]:
import numpy as np
import sklearn as sk
import seaborn as sns
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os

x = tf.Variable(34, name = 'x')
y = tf.Variable(12, name = 'y')
z = tf.Variable(45, name = 'z')
f = pow(x,3)+pow(x,2)*y +y*z

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    result = f.eval()
    print(result)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
53716


In [11]:
a1 = tf.constant(3)
a2 = a1 +12
a3 = a2 -8

with tf.Session() as sess:
    #init = tf.global_variables_initializer()
    init.run()
    a = a3.eval()
    print(a)

7


In [12]:
m = tf.ones((20,5))
n = tf.zeros((5,20))
k = tf.ones((5,5))

y = tf.matmul(n,m) + k

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    matrix = y.eval()
    
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# Matrix determinant
arr = np.array([[2.0,4.0,6.6],
                [6.6,8.2,1.1],
                [7.4,4.1,2.9]])
v= tf.matrix_determinant(arr)
with tf.Session() as sess:
    out = v.eval()
    print(out)

-227.352


In [14]:
# matrix inverse  
inv_mat = tf.matrix_inverse(arr)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    inv = inv_mat.eval()
    print(inv)

[[-0.08475844 -0.06800028  0.21869172]
 [ 0.04838312  0.18930997 -0.18192055]
 [ 0.14787642 -0.09412717  0.04398466]]


In [15]:
# confusion matrix
a = tf.random_uniform((90,),minval = 0, maxval = 1)
b = tf.random_uniform((90,), minval = 0, maxval =1)
pred = tf.round(a, 'pred')
y_true = tf.round(b,'y_true')
confusion_mat = tf.confusion_matrix(pred, y_true, name = 'confusion_Matrix')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(confusion_mat.eval())

[[32 13]
 [22 23]]


In [16]:
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [17]:

Scalar = tf.constant(2)
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries) :\n %s \n" % Vector)

print ("Matrix (3x3 entries):\n %s \n" % Matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Scalar (1 entry):
 Tensor("Const_1:0", shape=(), dtype=int32) 

Vector (3 entries) :
 Tensor("Const_2:0", shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 Tensor("Const_3:0", shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 Tensor("Const_4:0", shape=(3, 3, 3), dtype=int32) 



In [18]:
v = tf.Variable(0)

In [19]:
@tf.function
def increment_by_one(v):
        v = tf.add(v,1)
        return v

In [20]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

Tensor("StatefulPartitionedCall:0", shape=(), dtype=int32)
Tensor("PartitionedCall:0", shape=(), dtype=int32)
Tensor("PartitionedCall_1:0", shape=(), dtype=int32)


In [21]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)


print ('c =: %s' % c)
    
print ('d =: %s' % d)

c =: Tensor("Add_4:0", shape=(1,), dtype=int32)
d =: Tensor("Sub_1:0", shape=(1,), dtype=int32)


In [22]:
5+3*2%10-8*6

-37

In [23]:
A = [12, 34, 56]
B = [123, 456]

In [25]:
# transpose
trans = tf.matrix_transpose(inv_mat)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    trans_n = trans.eval()
    print(trans_n)

[[-0.08475844  0.04838312  0.14787642]
 [-0.06800028  0.18930997 -0.09412717]
 [ 0.21869172 -0.18192055  0.04398466]]


In [29]:
# placeholders are like inputs to dummy containers
# they hold informations to be processed.

A = tf.placeholder(tf.float32, shape = (None,2))
B = A + 5

with tf.Session() as sess:
    b_val = B.eval(feed_dict = {A:[[1,2]]})
    b_val_u = B.eval(feed_dict = {A:[[4,5],[7,8], [9, 10]]})
print(b_val_u)

[[ 9. 10.]
 [12. 13.]
 [14. 15.]]
